spring:
  cloud:
    gateway:

      routes:
        - id: route_grafana
          uri: https://grafana-cf-mysql.readacted-domain.com
          predicates:
            - Host=**
          filters:
#            - PreserveHostHeader
            - SetRequestHostHeader=grafana-cf-mysql.readacted-domain.com
# Pass token to service instance permission endpoint ? See https://docs.spring.io/spring-cloud/docs/Hoxton.SR7/reference/htmlsingle/#token-relay
#            - TokenRelay=

      # https://cloud.spring.io/spring-cloud-gateway/reference/html/#troubleshooting
      httpserver:
        wiretap: true

      httpclient:
        wiretap: true

      # https://cloud.spring.io/spring-cloud-gateway/reference/html/#tls-and-ssl
      # ignore shield TLS cert for now
        ssl:
          useInsecureTrustManager: true

         # Instruct http client to use an outgoing http proxy
         # See https://github.com/spring-cloud/spring-cloud-gateway/issues/176#issuecomment-554674253
        proxy:
          host: ${osbreverseproxy.http_proxy.host}
          port: ${osbreverseproxy.http_proxy.port}
# https://cloud.spring.io/spring-cloud-gateway/reference/html/#tls-and-ssl
#server:
#  ssl:
#    enabled: true
#    key-alias: scg
#    key-store-password: scg1234
#    key-store: classpath:scg-keystore.p12
#    key-store-type: PKCS12


logging:
  level:
    reactor:
      netty: debug
    org:
      springframework:
        cloud:
          gateway: debug

        web:
          reactive:
            socket:
              server: debug
#                support: debug
        security: debug

