spring:
  cloud:
    gateway:

      routes:
        - id: route_grafana
          uri: https://grafana-cf-mysql.readacted-domain.com
          predicates:
            - Host=**
          filters:
#            - PreserveHostHeader
            - SetRequestHostHeader=grafana-cf-mysql.readacted-domain.com
# Pass token to service instance permission endpoint ? See https://docs.spring.io/spring-cloud/docs/Hoxton.SR7/reference/htmlsingle/#token-relay
#            - TokenRelay=

      # https://cloud.spring.io/spring-cloud-gateway/reference/html/#troubleshooting
      httpserver:
        wiretap: true

      httpclient:
        wiretap: true

      # https://cloud.spring.io/spring-cloud-gateway/reference/html/#tls-and-ssl
      # ignore shield TLS cert for now
        ssl:
          useInsecureTrustManager: true

# https://cloud.spring.io/spring-cloud-gateway/reference/html/#tls-and-ssl
#server:
#  ssl:
#    enabled: true
#    key-alias: scg
#    key-store-password: scg1234
#    key-store: classpath:scg-keystore.p12
#    key-store-type: PKCS12

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: osbcmdb-proxy0
            client-secret: Hibor0gocguj
            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/gateway"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            # See https://docs.cloudfoundry.org/services/dashboard-sso.html
            scope: openid,cloud_controller_service_permissions.read
        provider:
          uaa:
            authorization-uri: https://uaa.readacted-domain.com/oauth/authorize
            token-uri: https://uaa.readacted-domain.com/oauth/token
            user-info-uri: https://uaa.readacted-domain.com/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://uaa.readacted-domain.com/token_keys

# uaac client add osbcmdb-proxy0 --scope 'openid,cloud_controller_service_permissions.read' -s 'Hibor0gocguj' --authorized_grant_types 'authorization_code,refresh_token' --redirect_uri 'https://osbcmdbproxy0.readacted-domain.com/' --authorities 'uaa.resource'
  #  scope: cloud_controller_service_permissions.read openid
  #  client_id: osbcmdb-proxy0
  #  resource_ids: none
  #  authorized_grant_types: refresh_token authorization_code
  #  redirect_uri: https://osbcmdbproxy0.readacted-domain.com/
  #  autoapprove:
  #  authorities: uaa.resource
  #  name: osbcmdb-proxy0
  #  required_user_groups:
  #  lastmodified: 1596558778404
  #  id: osbcmdb-proxy0

logging:
  level:
    reactor:
      netty: debug
    org:
      springframework:
        cloud:
          gateway: debug

        web:
          reactive:
            socket:
              server: debug
#                support: debug
        security: debug

