spring:
  application:
    name: "osb-reverse-proxy-template" # required for opentracing. should be overriden in symlinked copies

# turn on actuator endpoints protected by basic auth
# including spring cloud gateway specific endpoint, see https://cloud.spring.io/spring-cloud-gateway/reference/html/#actuator-api
management:
  endpoint:
    beans:
      enabled: true
    conditions:
      enabled: true
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      enabled: true
    httptrace:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true

  # make enabled endpoints accessible over web. setting "*" seems to expose also non enabled endpoints
  endpoints:
    web:
      exposure:
        include: "beans,conditions,info,gateway,health,httptrace,loggers,metrics,threaddump"



